[profile.release]
panic = 'unwind'

[workspace]
members = [
	"merkle-distributor",
	"zenlink-protocol",
	"zenlink-protocol/rpc",
	"zenlink-protocol/rpc/runtime-api",
	"zenlink-stable-amm",
	"zenlink-stable-amm/rpc",
	"zenlink-stable-amm/rpc/runtime-api",
	"zenlink-swap-router",
]

resolver = "2"

[workspace.dependencies]
zenlink-protocol               = { path = "zenlink-protocol", default-features = false }
zenlink-protocol-runtime-api   = { path = "zenlink-protocol/rpc/runtime-api", default-features = false}
zenlink-stable-amm             = { path = "zenlink-stable-amm", default-features = false }
zenlink-stable-amm-runtime-api = { path = "zenlink-stable-amm/rpc/runtime-api", default-features = false }

codec                   = { package = "parity-scale-codec", version = "3.7.5", default-features = false }
hex-literal             = { version = "0.4.1" }
scale-info = { version = "2.11.6", default-features = false, features = ["derive"] }
serde = { version = "1.0.214", default-features = false }
serde_json              = { version = "1.0.132", default-features = false  }
jsonrpsee               = { version = "0.24.3", features = ["server", "macros", "client"] }

cumulus-primitives-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
frame-benchmarking      = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
frame-support           = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
frame-system            = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
pallet-balances         = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
pallet-timestamp        = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
sp-api                  = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
sp-arithmetic           = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
sp-blockchain           = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
sp-core                 = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
sp-io                   = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
sp-rpc                  = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
sp-runtime              = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
sp-std                  = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", default-features = false }
xcm                     = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2603", package = "staging-xcm", default-features = false }

orml-tokens             = { git = "https://github.com/bifrost-io/open-runtime-module-library", branch = "release-polkadot-stable2603", default-features = false }
orml-traits             = { git = "https://github.com/bifrost-io/open-runtime-module-library", branch = "release-polkadot-stable2603", default-features = false }
